### ISSUE TITLE
Module not working for Prestashop 1.7.3

### ISSUE THREAD

**Issue by gnanarajps17** [razorpay/razorpay-prestashop#21]
throwing
![err2](https://user-images.githubusercontent.com/48401522/54081544-50849900-432c-11e9-8af9-fac0e9ea4aeb.png)
 error once we pay through Razor pay. Razorpay payment id is blank.

**Comment by gnanarajps17** [comment]
Prestashop version 1.7.3 and PHP 7.1

**Comment by rushabrdx** [comment]
> Prestashop version 1.7.3 and PHP 7.1

Just an update . turn on terms and condition check box and see of it works.

**Comment by ramth05** [comment]
#28

**Comment by madhanmdkm** [comment]
Prestashop 1.7.6.4 same error after enabled terms and condition checkbox

**Comment by ramth05** [comment]
@madhanmdkm , which version of plugin you are using? I have verified latest version **2.3.4** of plugin and it's working fine with base theme in Prestashop 1.7.6.4.

**Comment by madhanmdkm** [comment]
Due to sp one page checkout and term and condition not enabled it was not
working now it is working fine. Thank you:)

**Comment by kavbazaar** [comment]
hello same theme sp topmart but razorpay not working and i want razor pay how to do that can any one help me out in this
