### ISSUE TITLE
Error: The payment id provided is null

### ISSUE THREAD

**Issue by madhanmdkm** [razorpay/razorpay-prestashop#28]
Error! Please contact the seller directly for assistance.
Order Id: 25
Razorpay Payment Id: 
Error: The payment id provided is null

When i integrate with payment gateway im getting above error

**Comment by madhanmdkm** [comment]
PrestaShop version: 1.7.5.2

**Comment by rushabrdx** [comment]
They wont provide any support or updates. Been trying for an year.

**Comment by ramth05** [comment]
> PrestaShop version: 1.7.5.2
@madhanmdkm 
Can you please try the latest release and check it.

**Comment by rushabrdx** [comment]
> > PrestaShop version: 1.7.5.2
> > @madhanmdkm
> > Can you please try the latest release and check it.

Still the same issue tried it.

**Comment by madhanmdkm** [comment]
> > > PrestaShop version: 1.7.5.2
> > > @madhanmdkm
> > > Can you please try the latest release and check it.
> 
> Still the same issue tried it.

May i know which one you are using alternatively

**Comment by rushabrdx** [comment]
> > > > PrestaShop version: 1.7.5.2
> > > > @madhanmdkm
> > > > Can you please try the latest release and check it.
> > 
> > 
> > Still the same issue tried it.
> 
> May i know which one you are using alternatively

Using Prestashop 1.7.5 and your latest version 2.1.0
Alternatively using Paytm and paypal

**Comment by ramth05** [comment]
@rushabrdx 
can you please provide some screens or site address where you are testing it.

**Comment by madhanmdkm** [comment]
> try the latest release and check it

Thats also tried.. No Luck.. :(

**Comment by madhanmdkm** [comment]
> @rushabrdx
> can you please provide some screens or site address where you are testing it.

https://github.com/razorpay/razorpay-prestashop/issues/28#issuecomment-512684340

which is available in this above url

**Comment by madhanmdkm** [comment]
> @rushabrdx
> can you please provide some screens or site address where you are testing it.
[](https://github.com/razorpay/razorpay-prestashop/issues/28#issuecomment-512684340)

**Comment by madhanmdkm** [comment]
![image](https://user-images.githubusercontent.com/32380176/61434790-8d087700-a954-11e9-8e5c-687a3252ef12.png)

**Comment by rushabrdx** [comment]
> > @rushabrdx
> > can you please provide some screens or site address where you are testing it.

The scree provided by @madhanmdkm is the same exact screen i get. the site is siddhisilver.in but i removed razorpay because the site is live. You can check it at madhanmdkm's site.

**Comment by ramth05** [comment]
@madhanmdkm site also razorpay module not enabled. Is the payment ID gets generated in razorpay account transactions?

**Comment by rushabrdx** [comment]
> @madhanmdkm site also razorpay module not enabled. Is the payment ID gets generated in razorpay account transactions?

Nothing gets generated in the accounts.

**Comment by rushabrdx** [comment]
> @madhanmdkm site also razorpay module not enabled. Is the payment ID gets generated in razorpay account transactions?

I have enabled it for you to check. Please check so i can disable it again.

**Comment by ramth05** [comment]
@rushabrdx 
Can you please check if you are able to hit razorpay API from your site and port 443 is enabled ?

**Comment by rushabrdx** [comment]
> @rushabrdx
> Can you please check if you are able to hit razorpay API from your site and port 443 is enabled ?

Advice on how to do it please?

**Comment by ramth05** [comment]
please check it with your network team.

**Comment by ramth05** [comment]
create a support ticket in razorpay

**Comment by rushabrdx** [comment]
> @rushabrdx
> Can you please check if you are able to hit razorpay API from your site and port 443 is enabled ?

Port 443 Is open.
also have created countless tickets in razorpay. its waste of time.

**Comment by ramth05** [comment]
We need clone/development version of your site to look into this issue further with razorpay enabled.

**Comment by rushabrdx** [comment]
> We need clone/development version of your site to look into this issue further with razorpay enabled.

You can check on my live webiste. even on fresh 1.7.5 in test mode it does not work.

**Comment by madhanmdkm** [comment]
stroqy.com Please try in this site

**Comment by ramth05** [comment]
This issue looks like conflict with your theme custom Javascript. Can you please try to disable other online payment methods and try it. Or just try with prestashop basic theme.

**Comment by madhanmdkm** [comment]
Already i try using basic theme bu no luck:(

**Comment by ramth05** [comment]
ok. Can you please try to enable Terms of Service form order settings in backend, and check it

**Comment by ramth05** [comment]
@madhanmdkm 

Can you please try to enable Terms of Service form Shop Parameters -> order settings, in backend, and try it.

**Comment by madhanmdkm** [comment]
![image](https://user-images.githubusercontent.com/32380176/61451685-90612a00-a977-11e9-9065-a2167b8425c1.png)


![image](https://user-images.githubusercontent.com/32380176/61451722-b090e900-a977-11e9-9e09-cd1c4450940f.png)

**Comment by madhanmdkm** [comment]
still getting the same

**Comment by rushabrdx** [comment]
> @madhanmdkm
> 
> Can you please try to enable Terms of Service form Shop Parameters -> order settings, in backend, and try it.

Can confirm this does not work. Throws the same error.

**Comment by rushabrdx** [comment]
> @rushabrdx
> So, it's looks like issue with Javascript conflict with the theme.
> If possible can you please try to disable other online payment options first and try. Another solution just test it with basic prestashop theme.

Ok now on clean install it works properly .

**Comment by rushabrdx** [comment]
So enabling terms and conditions now works for me. but can we disable that?
Dont want customers to agree to terms and conditions.

**Comment by ramth05** [comment]
@rushabrdx 
No, this looks like issue in current plugin. We will try to fix it in next release.

**Comment by rushabrdx** [comment]
> @rushabrdx
> No, this looks like issue in current plugin. We will try to fix it in next release.

Fix it soon as possible so can use razorpay as primary. Thanks a lot for the help.

**Comment by ramth05** [comment]
@rushabrdx , Can you please share the site link where it work fine for you?

**Comment by rushabrdx** [comment]
> @rushabrdx , Can you please share the site link where it work fine for you?

siddhisilver.in

**Comment by madhanmdkm** [comment]
> > @rushabrdx
> > So, it's looks like issue with Javascript conflict with the theme.
> > If possible can you please try to disable other online payment options first and try. Another solution just test it with basic prestashop theme.
> 
> Ok now on clean install it works properly .

Still im getting the issue
may i know what was the changes you done
 
simply reinstalled prestashop 1.7.5.2 or anything else

**Comment by madhanmdkm** [comment]
Basic theme its working for me

**Comment by rushabrdx** [comment]
> Basic theme its working for me

So razorpay is working on the basic theme?

**Comment by madhanmdkm** [comment]
> > Basic theme its working for me
> 
> So razorpay is working on the basic theme?

Yup... Its working in basic theme

**Comment by rushabrdx** [comment]
> > > Basic theme its working for me
> > 
> > 
> > So razorpay is working on the basic theme?
> 
> Yup... Its working in basic theme

Then check with the theme developer he will help. Where did you purchase it and does the theme had zen option>?

**Comment by madhanmdkm** [comment]
okay i will check with developer.. themeforest i purchased it. zen option?- i dont get it

**Comment by rushabrdx** [comment]
> themeforest

They might help . Zen option is an option when you purchase from prestashop addons. Gives you one year of support.

**Comment by madhanmdkm** [comment]
oh okay then i will touch with them thank you for your help:)

**Comment by madhanmdkm** [comment]
Now my site (stroqy.com) razorpay has enabled and working fine, but "Order with an obligation to pay" also showing, my question is whyi have 2 different buttons. If i click on this "Order with an obligation to pay"  button payment id null error im getting. Please advise

**Comment by ramth05** [comment]
@madhanmdkm, 
We have provided plugin based on basic theme. 
As currently, you have customised your theme and because of that things are not working properly.
Please check hows it's working fine in @rushabrdx site.

**Comment by rushabrdx** [comment]
> Now my site (stroqy.com) razorpay has enabled and working fine, but "Order with an obligation to pay" also showing, my question is whyi have 2 different buttons. If i click on this "Order with an obligation to pay" button payment id null error im getting. Please advise

I think that has something to do with the custom theme. on my website it shows the only option which the payment module provide overriding the shops default. again only person can help here is developer of your theme

**Comment by madhanmdkm** [comment]
Okay thank you for your reply

**Comment by madhanmdkm** [comment]
How to edit Order with an oblication to pay. Before clicking terms and condition check box im getting Order with an oblication to pay after check box click it automatically change as pay button.. Show how to change Order with an oblication to pay name as pay

**Comment by madhanmdkm** [comment]
Prestashop Sp One Step Checkout if its get enabled current razor pay not working.. Again getting the same issues

**Comment by rushabrdx** [comment]
> How to edit Order with an oblication to pay. Before clicking terms and condition check box im getting Order with an oblication to pay after check box click it automatically change as pay button.. Show how to change Order with an oblication to pay name as pay

You can edit it in translations>modules>cash on delievery or whatever module throws that 
or somewhere in the translations its there. can help you if you provide details.

**Comment by rushabrdx** [comment]
> Prestashop Sp One Step Checkout if its get enabled current razor pay not working.. Again getting the same issues

On the basic theme?

**Comment by ramth05** [comment]
@rushabrdx, are you using Razorpay webhook feature as for your prestashop site?

**Comment by rushabrdx** [comment]
> @rushabrdx, are you using Razorpay webhook feature as well for your prestashop site?

No. whats that feature anyway?

**Comment by ramth05** [comment]
> > @rushabrdx, are you using Razorpay webhook feature as well for your prestashop site?
> 
> No. whats that feature anyway?

Please check Razorpay documentation. https://razorpay.com/docs/webhooks/
If possible try to use it.

**Comment by rushabrdx** [comment]
> > > @rushabrdx, are you using Razorpay webhook feature as well for your prestashop site?
> > 
> > 
> > No. whats that feature anyway?
> 
> Please check Razorpay documentation. https://razorpay.com/docs/webhooks/
> If possible try to use it.

Sorry to dissappoint but im not an developer so wont be able to do it. i just know a few things here and there.

**Comment by madhanmdkm** [comment]
Could you please guide me, when i enable prestashop sp one step checkout using razorpay throws below error. If i disable sp one step checkout its working. Any idea how to fix this.
Below is the error::
Error! Please contact the seller directly for assistance.
Order Id: 25
Razorpay Payment Id:
Error: The payment id provided is null

**Comment by ramth05** [comment]
It's already supported for basic theme.

**Comment by Varkeychen** [comment]
Hi all

Me too hit with the same error -
Error! Please contact the seller directly for assistance.
Order Id: 31
Razorpay Payment Id:
Error: The payment id provided is null

I was using Knowband 'One Page Supercheckout' along with RazorPay. After disabling  'One Page Supercheckout' It works well without any problem. Still I am fully blank why RazorPay keeps quarreling with Knowband 'One Page Supercheckout'.
