### ISSUE TITLE
Razorpay PrestaShop Latest Module Install Failed

### ISSUE THREAD

**Issue by ankit7sethi** [razorpay/razorpay-prestashop#4]
Error: razorpay did not return a valid response on installation.
![capture](https://cloud.githubusercontent.com/assets/3744778/23094961/2d45250c-f628-11e6-9630-2e0e1bde871b.PNG)

**Comment by captn3m0** [comment]
Please follow the installation guide in https://github.com/razorpay/razorpay-prestashop#installation. The plugin currently doesn't work with the upload installation.

**Comment by captn3m0** [comment]
We have fixed this issue and our latest installation instructions should suffice.
