### ISSUE TITLE
Auto capture is broken in V1.7 - Plugin version 2.3

### ISSUE THREAD

**Issue by hitinder** [razorpay/razorpay-prestashop#41]
Hello Guys!
Auto capture is broken in the latest release of v1.7. It was working in previous built but in 2.3 it's broken and not capturing transactions again.

![image](https://user-images.githubusercontent.com/9841229/70424193-03cb1b80-1a80-11ea-8f51-c655084d70e1.png)

![image](https://user-images.githubusercontent.com/9841229/70424439-763bfb80-1a80-11ea-8d30-033695c5c298.png)

**Comment by hitinder** [comment]
Hey @harman28 take this latest release off asap. Orders are marked as paid in CMS but in actual they are not. This will only make merchants lose money.

@ramth05 @umsh1ume

**Comment by ramth05** [comment]
> Hey @harman28 take this latest release off asap. Orders are marked as paid in CMS but in actual they are not. This will only make merchants lose money.
> 
> @ramth05 @umanghome

@hitinder , The fix already applied yesterday to version 2.3.2. Please update it in your store.

**Comment by harman28** [comment]
@hitinder Noted, marked the bad versons as pre-releases and added a warning against usage.
