### ISSUE TITLE
Wont work on razorpay 

### ISSUE THREAD

**Issue by shivakadakol** [razorpay/razorpay-prestashop#45]
Getting a new error with this module. Nothing would happen when you click pay no matter how many times. 
Heres an screenshot of error from google console.
http://prnt.sc/r26frd
**core.js:39 POST https://kolhapurkhanakhajana.com/module/razorpay/order 404 (Not Found)**
![razor pay](https://user-images.githubusercontent.com/25544349/74515304-54ee0480-4f34-11ea-96c6-3551886b5e20.png)
Error is

**Comment by PraveenGirishNadumani** [comment]
Try enabling the search friendly URLs.
this can be done from from Configure -> Shop Parameters -> Trafic & SEO. Under setup URL's section.

**Comment by ramth05** [comment]
Closing as this issue already fixed in latest release.
