### ISSUE TITLE
Sp one step checkout enabled razorpay throws error

### ISSUE THREAD

**Issue by madhanmdkm** [razorpay/razorpay-prestashop#47]
If i enabled sp one step checkout with razorpay it get below error. Normal checkout works fine. Due to that i disabled this razorpay in my website. Please guide me what to do.
error.
Error! Please contact the seller directly for assistance.
Order Id: 25
Razorpay Payment Id:
Error: The payment id provided is null

**Comment by ramth05** [comment]
@madhanmdkm , Can you please share some more details of this, like which addons it is and addons link. If it's paid can you please provide us some clone of your site where we should test it and guide you further on it.

**Comment by madhanmdkm** [comment]
https://stroqy.com
Select payment method as pay by razorpay then you will get exact error

**Comment by ramth05** [comment]
> https://stroqy.com
> Select payment method as pay by razorpay then you will get exact error

@madhanmdkm, this looks customised solution. Is this test/clone site? if yes can you please pass me the FTP details here "amprakash.singh@razorpay.com" to check it. or if you can help me to install this addon locally.

**Comment by ramth05** [comment]
Currently supporting all the theme based on basic theme.

**Comment by anishmenon** [comment]
> If it's paid can you please provide us some clone of your site where we should test it and guide you further on it.



> Currently supporting all the theme based on basic theme.

After successful payment its redirecting me to normal html with message

Cart cannot be loaded or an order has already been placed using this cart


instead of redirecting to order confirmation
