### ISSUE TITLE
After instelling the module the size shows error and now the site is not visible saying...

### ISSUE THREAD

**Issue by debasishsinh** [razorpay/razorpay-prestashop#48]
After instelling the module the size shows error and now the site is not visible saying... 
[PrestaShop] Fatal error in module file :/home/insysdc1/storeella.com/classes/module/Module.php(1361) : eval()'d code:
syntax error, unexpected 'use' (T_USE)
![image](https://user-images.githubusercontent.com/64264476/80215619-6bae8700-865a-11ea-90e0-5d6d74440ceb.png)

**Comment by ramth05** [comment]
> After instelling the module the size shows error and now the site is not visible saying...
> [PrestaShop] Fatal error in module file :/home/insysdc1/storeella.com/classes/module/Module.php(1361) : eval()'d code:
> syntax error, unexpected 'use' (T_USE)
> ![image](https://user-images.githubusercontent.com/64264476/80215619-6bae8700-865a-11ea-90e0-5d6d74440ceb.png)

@debasishsinh , Can you please some more details, like which PS version and module version you are using.

**Comment by ramth05** [comment]
@debasishsinh , closing this issue because things are working with other merchants. Please feel free to reopen it, if still facing issue.

**Comment by debasishsinh** [comment]
Hi , Sorry for late reply. 
Well I was installed 1.7 while i was running 1.6  so later on when i removed 1.7 and installed 1.6 module it started working perfectly but there was some issue with the razorpay so i was busy to resolve that so not able to reply on time to close the issue. 


Thanks And Regards

https://www.insysd.com/

Debasish Sinha

CEO & MD

M: +91-7005467436


https://www.facebook.com/InsysdCorp/

https://twitter.com/Insysd

https://in.linkedin.com/company/insysd?trk=public_profile_topcard_current_company










E: mailto:debasishsinha@insysd.com | W: https://www.insysd.com/














P Please do not print this email unless it is absolutely necessary

The company accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.
























---- On Wed, 06 May 2020 15:26:21 +0530 Ram Prakash Singh <mailto:notifications@github.com> wrote ----




https://github.com/debasishsinh , closing this issue because things are working with other merchants. Please feel free to reopen it, if still facing issue.
