### ISSUE TITLE
Breaks the website and causes the 524 & 503 error

### ISSUE THREAD

**Issue by hitinder** [razorpay/razorpay-prestashop#51]
Congratulations guys! Once again your guys managed to break my website.
The site became extremely slow. It won't move past step 2 of the cart and breaks the website with error 503. For cloudflare, it would show 524 error.

Disabling the plugin does the magic and everything starts working like a charm.

I have disabled and removed the plugin from my store. Thanks & good luck!

![image](https://user-images.githubusercontent.com/9841229/83974085-52ecee80-a8f3-11ea-82cb-28fa661522e6.png)

**Comment by ramth05** [comment]
@hitinder , can you please let us know which version of razorpay plugins and Presta-shop it breaks.

**Comment by hitinder** [comment]
Plugin v2.3.5
PrestaShop v1.7.5.1

**Comment by ramth05** [comment]
@hitinder, We have tested the plugin for with above details and it's working fine. Is it possible for you to create some clone site on your server to test around this issue?

**Comment by hitinder** [comment]
@ramth05 We have other payment plugins like PayTm and PayPal that are enabled and working. May be your plugin isn't compatible with these. This (5xx) is the same issue that I have reported earlier about the previous version of your plugin.

At present, we can't set up a clone for you. If we can, we will, and notify you here. Just note that after uninstalling your plugin everything was working fine.

**Comment by hitinder** [comment]
Hello Team!
We can confirm that this issue is to do with Prestashop and not with the plugin. Prestashop will return a 503 error when a coupon code that has free shipping is applied to the cart.

Regards,
Hitin
