### ISSUE TITLE
Shows error after payment is made

### ISSUE THREAD

**Issue by additionsolutions** [razorpay/razorpay-prestashop#54]
Currently testing in Test Mode.
Payment is captured successfully but user sees error page after payment.

After payment following url is called:
https://arba-fashion.com/en/module/razorpay/validation?razorpay_payment_id=pay_FENXkHNduY0grC

but message displayed as :

This page isn’t working 
arba-fashion.com is currently unable to handle this request.
HTTP ERROR 500
<Reload>

I'm using Presatshop version 1.7.6.7 and razorpay-prestashop version 2.1.0

Do I missed any configuration?

**Comment by ramth05** [comment]
@additionsolutions 

> Currently testing in Test Mode.
> Payment is captured successfully but user sees error page after payment.
> 
> After payment following url is called:
> https://arba-fashion.com/en/module/razorpay/validation?razorpay_payment_id=pay_FENXkHNduY0grC
> 
> but message displayed as :
> 
> This page isn’t working
> arba-fashion.com is currently unable to handle this request.
> HTTP ERROR 500
> I'm using Presatshop version 1.7.6.7 and razorpay-prestashop version 2.1.0
> 
> Do I missed any configuration?

@additionsolutions , Why you are trying old version of plugin, Can you please update it to latest one and verify if you are facing same issue here as well.

**Comment by additionsolutions** [comment]
I downloaded  that version from razorpay website, may be its not updated there.
Anyway I installed version 2.3.5 now but getting following errror:

Error! Please contact the seller directly for assistance.
Order Id: 12
Razorpay Payment Id: pay_FEOjl8DEgiHzwd
Error: Invalid signature passed

Tried regenerating keys but same issue.

**Comment by additionsolutions** [comment]
Cleared cache and tried again.
Now its back to old problem:

This page isn’t working 
arba-fashion.com is currently unable to handle this request.
HTTP ERROR 500

While trying to access: 
https://arba-fashion.com/en/module/razorpay/validation?razorpay_payment_id=pay_FEOwdbGB9UpYl7

**Comment by ramth05** [comment]
> Cleared cache and tried again.
> Now its back to old problem:
> 
> This page isn’t working
> arba-fashion.com is currently unable to handle this request.
> HTTP ERROR 500
> 
> While trying to access:
> https://arba-fashion.com/en/module/razorpay/validation?razorpay_payment_id=pay_FEOwdbGB9UpYl7

@additionsolutions , Can you please uninstall this plugin. Then login to FTP and clear the `razorpay` folder from modules and clear the cache. Install the module again and try it. 
If not works, please pass me your site and FTP details to debug the issue on your site.

**Comment by additionsolutions** [comment]
Tried again with all steps you mentioned. But same problem.
Please give me your email for sending site details and FTP login.

**Comment by additionsolutions** [comment]
Site has multiple languages and multi currency. Anything because of this??

**Comment by ramth05** [comment]
> Site has multiple languages and multi currency. Anything because of this??

@additionsolutions , Please pass the site details here `ramprakash.singh@razorpay.com`

**Comment by ramth05** [comment]
Closing it, please feel free to reopen if still same issue.
