### ISSUE TITLE
Not able to create back office orders

### ISSUE THREAD

**Issue by Chiccee** [razorpay/razorpay-prestashop#55]
Hi, 

I am using Presta 1.6.1.24 version and trying to integrate Razorpay 1.4.1 using API keys integration method. 

The installation and configuration is done but Razorpay is not seen as one of the payment methods in Back office 

In Live mode, the payment is deducted, but order is not created and Cart continues to have products. 
Money is transferred to Razorpay account and mail is sent to customer, but does not appear in order historry of customer account or Back office of website 

Please help, this is urgent - I have been trying to do everything since last 3 days 

Note - I am not a programmer, so a solution without altering codes would be appreciated

**Comment by ramth05** [comment]
> Hi,
> 
> I am using Presta 1.6.1.24 version and trying to integrate Razorpay 1.4.1 using API keys integration method.
> 
> The installation and configuration is done but Razorpay is not seen as one of the payment methods in Back office
> 
> In Live mode, the payment is deducted, but order is not created and Cart continues to have products.
> Money is transferred to Razorpay account and mail is sent to customer, but does not appear in order historry of customer account or Back office of website
> 
> Please help, this is urgent - I have been trying to do everything since last 3 days
> 
> Note - I am not a programmer, so a solution without altering codes would be appreciated

@Chiccee , I have tested it and it's working fine. Please share more details like screen shots etc.

**Comment by Chiccee** [comment]
There are more than 1 shop in the Multistore 

1. Shop - My store - URL - www. chiccee.com/shop/ - this is the main and default shop and here the Razorpay is working fine

But 
2. Shop - C10001 - URL - www. chiccee.com/shop/C1001 - this is the second shop in the tree where this is not working. I have tried all methods, but not solving. Attached is the error. Payment gets through but order iis not created, either in Front office or back office 

<img width="1277" alt="Screen Shot 2020-07-20 at 6 11 56 PM" src="https://user-images.githubusercontent.com/68447064/87939372-9bccc100-cab5-11ea-8815-543d671361fe.png">


I read somewhere, as this is the virtual folder for URL, there could be as issue with URL rewriting not enabled. To enable that, I changed the setting in SEO and URLs, Friendly URL option to YES. 
But with this the entire site got distorted.

**Comment by Chiccee** [comment]
@ramth05 - need your help here man!
The complete site operation is stuck - Please help !!!

**Comment by ramth05** [comment]
> @ramth05 - need your help here man!
> The complete site operation is stuck - Please help !!!

@Chiccee , If it's multisite or SEO related issue you need to check with your developer. As you mentioned the plugin working fine with main store. So looks like no issue with the plugin.

**Comment by Chiccee** [comment]
@ramth05 

Just want to check that the Razorpay key is usable across multisite URLs also, right?
Coz the problem is that it works in 1 URL and does not in another

**Comment by ramth05** [comment]
> @ramth05
> 
> Just want to check that the Razorpay key is usable across multisite URLs also, right?
> Coz the problem is that it works in 1 URL and does not in another

Yes, It's should work.

**Comment by ramth05** [comment]
> @ramth05
> 
> Just want to check that the Razorpay key is usable across multisite URLs also, right?
> Coz the problem is that it works in 1 URL and does not in another

@Chiccee , No, you need to register your multiple sites with the razorpay. https://razorpay.com/docs/payment-gateway/web-integration/standard/

**Comment by ramth05** [comment]
Closing it as of now.
