### ISSUE TITLE
Issue with checkout

### ISSUE THREAD

**Issue by farrum** [razorpay/razorpay-prestashop#59]
We are using prestashop 1.7.6.3, using the 2.3.5 version of Razorpay. Php version 7.2. Module does not work on test mode. We kept it on the live with webhook active. 

In checkout, when the Razor Pay is selected, we are getting new button, but actual button remains along with it. Further after the transaction the module is remaining on the checkout page. The order also does not show in either the orders list, shopping cart or abandoned cart.

please suggest what could be the reason behind it.

**Comment by ramth05** [comment]
@farrum , Can you please let us know if you are using it with any custom theme.

**Comment by ramth05** [comment]
Closing it, as no reply.
