### ISSUE TITLE
Webhook Issue

### ISSUE THREAD

**Issue by cowherdboy** [razorpay/razorpay-prestashop#61]
Hello,

I had setup Webhook on Razorpay and enabled the same on the razorpay module (2.4.0) in Prestashop (1.7.6.4). There was a failed payment today on the Razorpay dashboard but I did not get any e-mail alert. How can I check if the Webhook is working as it should?

Regards,

**Comment by ramth05** [comment]
@cowherdboy, Currently plugin only supports `order.paid` Event.

**Comment by cowherdboy** [comment]
Ok. Thank you.
