### ISSUE TITLE
Razorpay won't show up in payments section

### ISSUE THREAD

**Issue by codez266** [razorpay/razorpay-prestashop#7]
Tried installing the module in both prestashop 1.6 and 1.7 but it won't show up in payments section, even after configuring the keys.

**Comment by captn3m0** [comment]
@codez266 This might have been a problem with version mismatch.

Our 1.3.x releases are supported in PrestaShop 1.6
2.x releases are supported in PrestaShop 1.7

Can you please try the latest 2.0.0 release against your 1.7 installation and let us know if that works?
