### ISSUE TITLE
Not working in PS 1.7.8.0

### ISSUE THREAD

**Issue by razarahil** [razorpay/razorpay-prestashop#76]
The module is not working in 1.7.8.0, it was working fine till 1.7.7.8 but after that, it stop showing up on the checkout page. Backend is still working fine, we can configure and add our details, even showing up in the Payment preference section but when you try to do shopping in the frontend, it won't show.

**Comment by itsmesubham** [comment]
Can we have a timeline from razorpay for supporting this version?

**Comment by ramth05** [comment]
@razarahil @itsmesubham , As we have tested the module working fine with v1.7.8.1 . Can you please share some screens where you are facing the issue.

**Comment by itsmesubham** [comment]
We are getting the payment successful but the order is not getting created in the Back office, there is no error logs or anything from what I have checked. I am running a test instance of prestashop on was lightsail. Currently its up at achatship.com with test payment mode, I will be happy to share the logs with you. 
Also is there some webhook which I need to call, post payment completion from the module? Am I missing something?

**Comment by ramth05** [comment]
> achatship.com

@itsmesubham , Can you please let me know for which shipping added you have set the shipping carrier to test this one https://www.achatship.com/

**Comment by razarahil** [comment]
It's start working for me after I reset the Module. I was getting an error in reset but somehow solved it.

**Comment by bhupendra7** [comment]
> @razarahil @itsmesubham , As we have tested the module working fine with v1.7.8.1 . Can you please share some screens where you are facing the issue.

I have tested with this version it is not working .. ValidateModule is not working, it is not called during call.

**Comment by bhupendra7** [comment]
Has anyone working site with this version.
